name: Markdown Quality Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Markdown Lint Check
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: "README.md"
